<?php

/**
 * BaseTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $part_id
 * @property integer $message_id
 * @property integer $lang_id
 * @property string $translated_text
 * @property boolean $is_fuzzy
 * @property boolean $is_autotrans
 * @property Language $Language
 * @property Message $Message
 * @property Part $Part
 * 
 * @method integer     getPartId()          Returns the current record's "part_id" value
 * @method integer     getMessageId()       Returns the current record's "message_id" value
 * @method integer     getLangId()          Returns the current record's "lang_id" value
 * @method string      getTranslatedText()  Returns the current record's "translated_text" value
 * @method boolean     getIsFuzzy()         Returns the current record's "is_fuzzy" value
 * @method boolean     getIsAutotrans()     Returns the current record's "is_autotrans" value
 * @method Language    getLanguage()        Returns the current record's "Language" value
 * @method Message     getMessage()         Returns the current record's "Message" value
 * @method Part        getPart()            Returns the current record's "Part" value
 * @method Translation setPartId()          Sets the current record's "part_id" value
 * @method Translation setMessageId()       Sets the current record's "message_id" value
 * @method Translation setLangId()          Sets the current record's "lang_id" value
 * @method Translation setTranslatedText()  Sets the current record's "translated_text" value
 * @method Translation setIsFuzzy()         Sets the current record's "is_fuzzy" value
 * @method Translation setIsAutotrans()     Sets the current record's "is_autotrans" value
 * @method Translation setLanguage()        Sets the current record's "Language" value
 * @method Translation setMessage()         Sets the current record's "Message" value
 * @method Translation setPart()            Sets the current record's "Part" value
 * 
 * @package    trad
 * @subpackage model
 * @author     eMerzh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTranslation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('translation');
        $this->hasColumn('part_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('message_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('lang_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('translated_text', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             ));
        $this->hasColumn('is_fuzzy', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('is_autotrans', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Language', array(
             'local' => 'lang_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Message', array(
             'local' => 'message_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Part', array(
             'local' => 'part_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}