<?php

/**
 * BaseTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $item_id
 * @property integer $lang_id
 * @property string $translated_text
 * @property boolean $is_fuzzy
 * @property boolean $is_autotrans
 * @property Item $Item
 * 
 * @method integer     getItemId()          Returns the current record's "item_id" value
 * @method integer     getLangId()          Returns the current record's "lang_id" value
 * @method string      getTranslatedText()  Returns the current record's "translated_text" value
 * @method boolean     getIsFuzzy()         Returns the current record's "is_fuzzy" value
 * @method boolean     getIsAutotrans()     Returns the current record's "is_autotrans" value
 * @method Item        getItem()            Returns the current record's "Item" value
 * @method Translation setItemId()          Sets the current record's "item_id" value
 * @method Translation setLangId()          Sets the current record's "lang_id" value
 * @method Translation setTranslatedText()  Sets the current record's "translated_text" value
 * @method Translation setIsFuzzy()         Sets the current record's "is_fuzzy" value
 * @method Translation setIsAutotrans()     Sets the current record's "is_autotrans" value
 * @method Translation setItem()            Sets the current record's "Item" value
 * 
 * @package    trad
 * @subpackage model
 * @author     eMerzh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTranslation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('translation');
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('lang_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('translated_text', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('is_fuzzy', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('is_autotrans', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Item', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}