<?php

/**
 * MessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessageTable extends Doctrine_Table
{
  /**
  * Returns an instance of this class.
  *
  * @return object MessageTable
  */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Message');
  }

  public function getCountForPart($part_id)
  {
    $q = Doctrine_Query::create()
      ->from('Message')
      ->where('part_id = ?',$part_id);
    return $q->count();
  }

  public function getMessagesForTranslation($part, $lang)
  {
    $q = Doctrine_Query::create()
    ->from('Message m')
    ->leftJoin('m.Translations t')
    ->where('m.part_id = ?', $part)
    ->andWhere('t.lang_id = ? or t.id is null', $lang);
      //Or to fetch null rows for non present translations
  return $q->execute();
  }
}