<?php

/**
 * PartTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PartTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PartTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Part');
    }
}