<?php

/**
 * TranslationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TranslationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TranslationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Translation');
    }
}