Language:
  columns:
    name: { type: string(255), notnull: true}
    code: { type: string(255), notnull: true, unique: true }

Part:
  columns:
    name: { type: string(255), notnull: true}

Message:
  actAs: { Timestampable: ~ }
  columns:
    part_id: { type: integer, notnull: true }
    original_text: { type: string, notnull: true}
  relations:
    Part: { onDelete: CASCADE, local: part_id, foreign: id, foreignAlias: Messages } 
  indexes:
    part_msg:
      fields: [part_id, original_text]
      type: unique

# TranslatedPart:
#   columns:
#     part_id: { type: integer, notnull: true }
#     lang_id: { type: integer, notnull: true }
#   relations:
#     Part: { onDelete: CASCADE, local: part_id, foreign: id, foreignAlias: TranslatedParts } 
#     Language: { onDelete: CASCADE, local: lang_id, foreign: id, foreignAlias: TranslatedParts }
# 

Translation:
  actAs: { Timestampable: ~ }
  columns:
    part_id: { type: integer, notnull: true }
    message_id: { type: integer, notnull: true }
    lang_id: { type: integer, notnull: true }
    translated_text: { type: string, notnull: true, default: ''}
    is_fuzzy: { type: boolean, notnull: true, default: 1 }
    is_autotrans: { type: boolean, notnull: true, default: 1 }
  relations:
    Language: { onDelete: CASCADE, local: lang_id, foreign: id, foreignAlias: Translations }
    Message: { onDelete: CASCADE, local: message_id, foreign: id, foreignAlias: Translations }
    Part: { onDelete: CASCADE, local: part_id, foreign: id, foreignAlias: Messages } 
